name: Build and Test

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
  workflow_dispatch:

jobs:
  perl-job:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      # TODO - make customizable via workflow_dispatch inputs
      matrix:
        perl-version:
          - '5.42'
          - '5.32'
#          - 'latest'

    container:
      # https://hub.docker.com/r/perldocker/perl-tester
      image: perldocker/perl-tester:${{ matrix.perl-version }}     

    name: Perl ${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v5

      - name: Regular tests
        run: |
            cpanm --installdeps --notest .
            perl Makefile.PL
            make
            make test

      - name: Prepare for release tests
        run: |
            cpanm --installdep .
            cpanm --notest Test::CheckManifest Test::Pod::Coverage Pod::Coverage Test::Pod

      - name: Release tests
        env:
          RELEASE_TESTING: 1
        run: |
            perl Makefile.PL
            make
            make test
